In [13]:
import numpy as np  //initialization

In [14]:
a = np.zeros((3,3,3))

In [16]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
np.ones((2,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
np.ones((2,2,4), dtype = int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [19]:
np.full((2,2),"Data Science")

array([['Data Science', 'Data Science'],
       ['Data Science', 'Data Science']], dtype='<U12')

In [21]:
np.random.rand(5)

array([0.19492593, 0.73083871, 0.30142083, 0.19827594, 0.95612963])

In [22]:
np.random.rand(10)

array([0.64726135, 0.13927216, 0.17353291, 0.66692456, 0.58176728,
       0.28887049, 0.43801465, 0.01573795, 0.63010229, 0.62552702])

In [23]:
data = np.random.randint(4,8,(8,8))

In [24]:
data

array([[5, 7, 4, 4, 4, 7, 6, 5],
       [6, 5, 6, 7, 6, 6, 5, 4],
       [4, 6, 5, 6, 4, 7, 4, 7],
       [4, 7, 7, 7, 7, 5, 4, 6],
       [7, 5, 7, 4, 7, 7, 5, 5],
       [5, 7, 6, 6, 4, 4, 5, 7],
       [6, 5, 5, 5, 7, 7, 7, 4],
       [5, 5, 4, 7, 6, 6, 5, 6]])

In [25]:
x = np.random.randint(5,10,(10,10))

In [26]:
x

array([[5, 5, 9, 8, 7, 5, 5, 7, 7, 8],
       [5, 5, 6, 6, 5, 8, 8, 6, 7, 6],
       [7, 8, 9, 7, 6, 5, 7, 6, 8, 8],
       [6, 5, 7, 9, 7, 7, 8, 5, 9, 8],
       [6, 9, 8, 7, 9, 6, 5, 5, 9, 7],
       [5, 9, 7, 5, 5, 7, 6, 9, 6, 5],
       [7, 8, 9, 6, 8, 9, 5, 6, 9, 9],
       [7, 6, 8, 7, 9, 7, 6, 5, 6, 6],
       [5, 8, 6, 7, 5, 6, 9, 9, 7, 5],
       [5, 6, 7, 8, 9, 8, 9, 8, 5, 8]])

In [30]:
x[4:6]  

array([[6, 9, 8, 7, 9, 6, 5, 5, 9, 7],
       [5, 9, 7, 5, 5, 7, 6, 9, 6, 5]])

In [32]:
x[4:8,4:6]

array([[9, 6],
       [5, 7],
       [8, 9],
       [9, 7]])

In [33]:
x[4:6,4:6]

array([[9, 6],
       [5, 7]])

In [36]:
d1 = np.random.randint(5,15,size=(5,3)) 

In [37]:
d2 = np.random.randint(5,15,size=(5,3))

In [38]:
np.hstack([d1, d2])

array([[14,  8,  5, 10, 13,  5],
       [11, 13, 13,  7, 13,  9],
       [12, 11, 10,  7, 14, 14],
       [14,  8,  6,  5, 10,  9],
       [ 8, 12,  6,  5,  9,  5]])

In [39]:
np.vstack([d1,d2])

array([[14,  8,  5],
       [11, 13, 13],
       [12, 11, 10],
       [14,  8,  6],
       [ 8, 12,  6],
       [10, 13,  5],
       [ 7, 13,  9],
       [ 7, 14, 14],
       [ 5, 10,  9],
       [ 5,  9,  5]])

In [42]:
np.concatenate([d1, d2] , axis=1)

array([[14,  8,  5, 10, 13,  5],
       [11, 13, 13,  7, 13,  9],
       [12, 11, 10,  7, 14, 14],
       [14,  8,  6,  5, 10,  9],
       [ 8, 12,  6,  5,  9,  5]])

In [43]:
d1 = np.random.randint(5,15,size=(5,3,2))

In [44]:
d2 = np.random.randint(5,15,size=(5,3,2))

In [45]:
np.concatenate([d1 , d2], axis = 2)

array([[[14,  7, 11, 11],
        [14,  9,  9,  7],
        [ 5,  8,  9,  6]],

       [[11,  6,  7,  9],
        [ 5,  8, 11, 12],
        [ 7,  8,  6, 11]],

       [[ 9, 13, 10,  8],
        [ 6, 14,  8,  9],
        [ 9, 10,  5,  6]],

       [[14, 11,  7, 10],
        [11, 11,  5,  5],
        [ 5, 11, 14, 12]],

       [[ 6,  9,  7,  5],
        [11,  7, 12,  9],
        [ 7, 13, 11, 11]]])

In [46]:
a1,a2 = np.hsplit(x,[5])
a1

array([[5, 5, 9, 8, 7],
       [5, 5, 6, 6, 5],
       [7, 8, 9, 7, 6],
       [6, 5, 7, 9, 7],
       [6, 9, 8, 7, 9],
       [5, 9, 7, 5, 5],
       [7, 8, 9, 6, 8],
       [7, 6, 8, 7, 9],
       [5, 8, 6, 7, 5],
       [5, 6, 7, 8, 9]])

In [47]:
b1,b2,b3 = np.vsplit(data,[5,7])

In [48]:
b1

array([[5, 7, 4, 4, 4, 7, 6, 5],
       [6, 5, 6, 7, 6, 6, 5, 4],
       [4, 6, 5, 6, 4, 7, 4, 7],
       [4, 7, 7, 7, 7, 5, 4, 6],
       [7, 5, 7, 4, 7, 7, 5, 5]])

In [49]:
b2

array([[5, 7, 6, 6, 4, 4, 5, 7],
       [6, 5, 5, 5, 7, 7, 7, 4]])

In [50]:
b3

array([[5, 5, 4, 7, 6, 6, 5, 6]])

In [51]:
x.shape

(10, 10)

In [52]:
x.ndim

2

In [53]:
data.size

64

In [56]:
x.reshape(2,50)

array([[5, 5, 9, 8, 7, 5, 5, 7, 7, 8, 5, 5, 6, 6, 5, 8, 8, 6, 7, 6, 7, 8,
        9, 7, 6, 5, 7, 6, 8, 8, 6, 5, 7, 9, 7, 7, 8, 5, 9, 8, 6, 9, 8, 7,
        9, 6, 5, 5, 9, 7],
       [5, 9, 7, 5, 5, 7, 6, 9, 6, 5, 7, 8, 9, 6, 8, 9, 5, 6, 9, 9, 7, 6,
        8, 7, 9, 7, 6, 5, 6, 6, 5, 8, 6, 7, 5, 6, 9, 9, 7, 5, 5, 6, 7, 8,
        9, 8, 9, 8, 5, 8]])

In [57]:
d = np.array([1,2,3,4,5,6,7,8,9])

In [58]:
d.ndim

1

In [59]:
d.shape

(9,)

In [60]:
d.size

9

In [65]:
x.reshape(-1,10)

array([[5, 5, 9, 8, 7, 5, 5, 7, 7, 8],
       [5, 5, 6, 6, 5, 8, 8, 6, 7, 6],
       [7, 8, 9, 7, 6, 5, 7, 6, 8, 8],
       [6, 5, 7, 9, 7, 7, 8, 5, 9, 8],
       [6, 9, 8, 7, 9, 6, 5, 5, 9, 7],
       [5, 9, 7, 5, 5, 7, 6, 9, 6, 5],
       [7, 8, 9, 6, 8, 9, 5, 6, 9, 9],
       [7, 6, 8, 7, 9, 7, 6, 5, 6, 6],
       [5, 8, 6, 7, 5, 6, 9, 9, 7, 5],
       [5, 6, 7, 8, 9, 8, 9, 8, 5, 8]])

In [67]:
np.sum(x)

688

In [68]:
np.sum(x, axis=1)

array([66, 62, 71, 71, 71, 64, 76, 67, 67, 73])

In [69]:
x

array([[5, 5, 9, 8, 7, 5, 5, 7, 7, 8],
       [5, 5, 6, 6, 5, 8, 8, 6, 7, 6],
       [7, 8, 9, 7, 6, 5, 7, 6, 8, 8],
       [6, 5, 7, 9, 7, 7, 8, 5, 9, 8],
       [6, 9, 8, 7, 9, 6, 5, 5, 9, 7],
       [5, 9, 7, 5, 5, 7, 6, 9, 6, 5],
       [7, 8, 9, 6, 8, 9, 5, 6, 9, 9],
       [7, 6, 8, 7, 9, 7, 6, 5, 6, 6],
       [5, 8, 6, 7, 5, 6, 9, 9, 7, 5],
       [5, 6, 7, 8, 9, 8, 9, 8, 5, 8]])

In [70]:
np.sin(x)

array([[-0.95892427, -0.95892427,  0.41211849,  0.98935825,  0.6569866 ,
        -0.95892427, -0.95892427,  0.6569866 ,  0.6569866 ,  0.98935825],
       [-0.95892427, -0.95892427, -0.2794155 , -0.2794155 , -0.95892427,
         0.98935825,  0.98935825, -0.2794155 ,  0.6569866 , -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849,  0.6569866 , -0.2794155 ,
        -0.95892427,  0.6569866 , -0.2794155 ,  0.98935825,  0.98935825],
       [-0.2794155 , -0.95892427,  0.6569866 ,  0.41211849,  0.6569866 ,
         0.6569866 ,  0.98935825, -0.95892427,  0.41211849,  0.98935825],
       [-0.2794155 ,  0.41211849,  0.98935825,  0.6569866 ,  0.41211849,
        -0.2794155 , -0.95892427, -0.95892427,  0.41211849,  0.6569866 ],
       [-0.95892427,  0.41211849,  0.6569866 , -0.95892427, -0.95892427,
         0.6569866 , -0.2794155 ,  0.41211849, -0.2794155 , -0.95892427],
       [ 0.6569866 ,  0.98935825,  0.41211849, -0.2794155 ,  0.98935825,
         0.41211849, -0.95892427, -0.2794155 

In [71]:
x.T

array([[5, 5, 7, 6, 6, 5, 7, 7, 5, 5],
       [5, 5, 8, 5, 9, 9, 8, 6, 8, 6],
       [9, 6, 9, 7, 8, 7, 9, 8, 6, 7],
       [8, 6, 7, 9, 7, 5, 6, 7, 7, 8],
       [7, 5, 6, 7, 9, 5, 8, 9, 5, 9],
       [5, 8, 5, 7, 6, 7, 9, 7, 6, 8],
       [5, 8, 7, 8, 5, 6, 5, 6, 9, 9],
       [7, 6, 6, 5, 5, 9, 6, 5, 9, 8],
       [7, 7, 8, 9, 9, 6, 9, 6, 7, 5],
       [8, 6, 8, 8, 7, 5, 9, 6, 5, 8]])

In [72]:
x.mean(axis=1)

array([6.6, 6.2, 7.1, 7.1, 7.1, 6.4, 7.6, 6.7, 6.7, 7.3])

In [73]:
x.std(axis=1)

array([1.42828569, 1.07703296, 1.13578167, 1.37477271, 1.5132746 ,
       1.49666295, 1.42828569, 1.1       , 1.48660687, 1.41774469])

In [74]:
v=np.array([1,2,3])

In [75]:
s=10

In [76]:
v+s

array([11, 12, 13])

In [78]:
t=[2,3]

In [79]:
#v+t

In [80]:
a = np.array([[1],[2],[3],[4],[5]])

In [81]:
a.shape

(5, 1)

In [82]:
a+v

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

In [83]:
a = np.random.randint(1,5,size=(10,2))


In [84]:
b = np.random.randint(1,5,size=(5,2))

In [85]:
a.reshape(1,10,2)

array([[[3, 3],
        [2, 4],
        [3, 3],
        [2, 4],
        [2, 1],
        [4, 3],
        [3, 2],
        [2, 4],
        [4, 4],
        [1, 1]]])

In [86]:
b.reshape(5,1,2) - a.reshape(1,10,2)

array([[[-2, -1],
        [-1, -2],
        [-2, -1],
        [-1, -2],
        [-1,  1],
        [-3, -1],
        [-2,  0],
        [-1, -2],
        [-3, -2],
        [ 0,  1]],

       [[ 0, -1],
        [ 1, -2],
        [ 0, -1],
        [ 1, -2],
        [ 1,  1],
        [-1, -1],
        [ 0,  0],
        [ 1, -2],
        [-1, -2],
        [ 2,  1]],

       [[ 1, -1],
        [ 2, -2],
        [ 1, -1],
        [ 2, -2],
        [ 2,  1],
        [ 0, -1],
        [ 1,  0],
        [ 2, -2],
        [ 0, -2],
        [ 3,  1]],

       [[ 1, -2],
        [ 2, -3],
        [ 1, -2],
        [ 2, -3],
        [ 2,  0],
        [ 0, -2],
        [ 1, -1],
        [ 2, -3],
        [ 0, -3],
        [ 3,  0]],

       [[ 0,  1],
        [ 1,  0],
        [ 0,  1],
        [ 1,  0],
        [ 1,  3],
        [-1,  1],
        [ 0,  2],
        [ 1,  0],
        [-1,  0],
        [ 2,  3]]])

In [87]:
a = np.random.randint(1,5,size=(10,2))
b = np.random.randint(1,5,size=(5,3))

In [88]:
a.shape

(10, 2)

In [89]:
b.shape

(5, 3)

In [90]:
a.reshape(1,10,1,2) - b.reshape(5,1,3,1)

array([[[[-1,  1],
         [-2,  0],
         [-1,  1]],

        [[-1, -2],
         [-2, -3],
         [-1, -2]],

        [[-1, -2],
         [-2, -3],
         [-1, -2]],

        [[ 0,  1],
         [-1,  0],
         [ 0,  1]],

        [[ 0,  0],
         [-1, -1],
         [ 0,  0]],

        [[-1, -1],
         [-2, -2],
         [-1, -1]],

        [[ 0, -2],
         [-1, -3],
         [ 0, -2]],

        [[-1, -1],
         [-2, -2],
         [-1, -1]],

        [[ 0, -2],
         [-1, -3],
         [ 0, -2]],

        [[ 0, -1],
         [-1, -2],
         [ 0, -1]]],


       [[[-2,  0],
         [-2,  0],
         [ 1,  3]],

        [[-2, -3],
         [-2, -3],
         [ 1,  0]],

        [[-2, -3],
         [-2, -3],
         [ 1,  0]],

        [[-1,  0],
         [-1,  0],
         [ 2,  3]],

        [[-1, -1],
         [-1, -1],
         [ 2,  2]],

        [[-2, -2],
         [-2, -2],
         [ 1,  1]],

        [[-1, -3],
         [-1, -3],
         [ 2,  0